package com.solo.erp.dao.mapper;

import com.solo.erp.dao.model.ErpInventoryInfo;
import com.solo.erp.dao.model.ErpInventoryInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ErpInventoryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_inventory_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    long countByExample(ErpInventoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_inventory_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int deleteByExample(ErpInventoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_inventory_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_inventory_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int insert(ErpInventoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_inventory_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int insertSelective(ErpInventoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_inventory_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    List<ErpInventoryInfo> selectByExampleWithRowbounds(ErpInventoryInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_inventory_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    List<ErpInventoryInfo> selectByExample(ErpInventoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_inventory_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    ErpInventoryInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_inventory_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") ErpInventoryInfo record, @Param("example") ErpInventoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_inventory_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByExample(@Param("record") ErpInventoryInfo record, @Param("example") ErpInventoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_inventory_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByPrimaryKeySelective(ErpInventoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_inventory_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByPrimaryKey(ErpInventoryInfo record);
}