package com.solo.erp.dao.mapper;

import com.solo.erp.dao.model.ErpMenuInfo;
import com.solo.erp.dao.model.ErpMenuInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ErpMenuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_menu_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    long countByExample(ErpMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_menu_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int deleteByExample(ErpMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_menu_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_menu_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int insert(ErpMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_menu_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int insertSelective(ErpMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_menu_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    List<ErpMenuInfo> selectByExampleWithRowbounds(ErpMenuInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_menu_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    List<ErpMenuInfo> selectByExample(ErpMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_menu_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    ErpMenuInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_menu_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") ErpMenuInfo record, @Param("example") ErpMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_menu_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByExample(@Param("record") ErpMenuInfo record, @Param("example") ErpMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_menu_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByPrimaryKeySelective(ErpMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_menu_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByPrimaryKey(ErpMenuInfo record);
}