package com.solo.erp.dao.mapper;

import com.solo.erp.dao.model.ErpOrderInfo;
import com.solo.erp.dao.model.ErpOrderInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ErpOrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_order_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    long countByExample(ErpOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_order_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int deleteByExample(ErpOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_order_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_order_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int insert(ErpOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_order_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int insertSelective(ErpOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_order_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    List<ErpOrderInfo> selectByExampleWithRowbounds(ErpOrderInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_order_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    List<ErpOrderInfo> selectByExample(ErpOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_order_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    ErpOrderInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_order_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") ErpOrderInfo record, @Param("example") ErpOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_order_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByExample(@Param("record") ErpOrderInfo record, @Param("example") ErpOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_order_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByPrimaryKeySelective(ErpOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_order_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByPrimaryKey(ErpOrderInfo record);
}