package com.solo.erp.dao.mapper;

import com.solo.erp.dao.model.ErpRoleMenuRel;
import com.solo.erp.dao.model.ErpRoleMenuRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ErpRoleMenuRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_role_menu_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    long countByExample(ErpRoleMenuRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_role_menu_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int deleteByExample(ErpRoleMenuRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_role_menu_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_role_menu_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int insert(ErpRoleMenuRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_role_menu_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int insertSelective(ErpRoleMenuRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_role_menu_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    List<ErpRoleMenuRel> selectByExampleWithRowbounds(ErpRoleMenuRelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_role_menu_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    List<ErpRoleMenuRel> selectByExample(ErpRoleMenuRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_role_menu_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    ErpRoleMenuRel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_role_menu_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") ErpRoleMenuRel record, @Param("example") ErpRoleMenuRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_role_menu_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByExample(@Param("record") ErpRoleMenuRel record, @Param("example") ErpRoleMenuRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_role_menu_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByPrimaryKeySelective(ErpRoleMenuRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_role_menu_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByPrimaryKey(ErpRoleMenuRel record);
}