package com.solo.erp.dao.mapper;

import com.solo.erp.dao.model.ErpStaffRoleRel;
import com.solo.erp.dao.model.ErpStaffRoleRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ErpStaffRoleRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_role_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    long countByExample(ErpStaffRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_role_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int deleteByExample(ErpStaffRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_role_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_role_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int insert(ErpStaffRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_role_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int insertSelective(ErpStaffRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_role_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    List<ErpStaffRoleRel> selectByExampleWithRowbounds(ErpStaffRoleRelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_role_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    List<ErpStaffRoleRel> selectByExample(ErpStaffRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_role_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    ErpStaffRoleRel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_role_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") ErpStaffRoleRel record, @Param("example") ErpStaffRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_role_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByExample(@Param("record") ErpStaffRoleRel record, @Param("example") ErpStaffRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_role_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByPrimaryKeySelective(ErpStaffRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_role_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByPrimaryKey(ErpStaffRoleRel record);
}