package com.solo.erp.dao.mapper;

import com.solo.erp.dao.model.ErpStaffInfo;
import com.solo.erp.dao.model.ErpStaffInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ErpStaffInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    long countByExample(ErpStaffInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int deleteByExample(ErpStaffInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int insert(ErpStaffInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int insertSelective(ErpStaffInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    List<ErpStaffInfo> selectByExampleWithRowbounds(ErpStaffInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    List<ErpStaffInfo> selectByExample(ErpStaffInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    ErpStaffInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") ErpStaffInfo record, @Param("example") ErpStaffInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByExample(@Param("record") ErpStaffInfo record, @Param("example") ErpStaffInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByPrimaryKeySelective(ErpStaffInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_staff_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByPrimaryKey(ErpStaffInfo record);
}