package com.solo.erp.dao.mapper;

import com.solo.erp.dao.model.ErpUidSequence;
import com.solo.erp.dao.model.ErpUidSequenceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ErpUidSequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_uid_sequence
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    long countByExample(ErpUidSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_uid_sequence
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int deleteByExample(ErpUidSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_uid_sequence
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_uid_sequence
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int insert(ErpUidSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_uid_sequence
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int insertSelective(ErpUidSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_uid_sequence
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    List<ErpUidSequence> selectByExampleWithRowbounds(ErpUidSequenceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_uid_sequence
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    List<ErpUidSequence> selectByExample(ErpUidSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_uid_sequence
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    ErpUidSequence selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_uid_sequence
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") ErpUidSequence record, @Param("example") ErpUidSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_uid_sequence
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByExample(@Param("record") ErpUidSequence record, @Param("example") ErpUidSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_uid_sequence
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByPrimaryKeySelective(ErpUidSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_uid_sequence
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByPrimaryKey(ErpUidSequence record);
}