package com.solo.erp.dao.mapper;

import com.solo.erp.dao.model.ErpVipRanks;
import com.solo.erp.dao.model.ErpVipRanksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ErpVipRanksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_ranks
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    long countByExample(ErpVipRanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_ranks
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int deleteByExample(ErpVipRanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_ranks
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_ranks
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int insert(ErpVipRanks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_ranks
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int insertSelective(ErpVipRanks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_ranks
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    List<ErpVipRanks> selectByExampleWithRowbounds(ErpVipRanksExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_ranks
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    List<ErpVipRanks> selectByExample(ErpVipRanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_ranks
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    ErpVipRanks selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_ranks
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") ErpVipRanks record, @Param("example") ErpVipRanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_ranks
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByExample(@Param("record") ErpVipRanks record, @Param("example") ErpVipRanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_ranks
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByPrimaryKeySelective(ErpVipRanks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_ranks
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    int updateByPrimaryKey(ErpVipRanks record);
}