package com.solo.erp.dao.mapper;

import com.solo.erp.dao.model.ErpVipInfo;
import com.solo.erp.dao.model.ErpVipInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ErpVipInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_info
     *
     * @mbg.generated Tue Jul 31 15:59:06 CST 2018
     */
    long countByExample(ErpVipInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_info
     *
     * @mbg.generated Tue Jul 31 15:59:06 CST 2018
     */
    int deleteByExample(ErpVipInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_info
     *
     * @mbg.generated Tue Jul 31 15:59:06 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_info
     *
     * @mbg.generated Tue Jul 31 15:59:06 CST 2018
     */
    int insert(ErpVipInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_info
     *
     * @mbg.generated Tue Jul 31 15:59:06 CST 2018
     */
    int insertSelective(ErpVipInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_info
     *
     * @mbg.generated Tue Jul 31 15:59:06 CST 2018
     */
    List<ErpVipInfo> selectByExampleWithRowbounds(ErpVipInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_info
     *
     * @mbg.generated Tue Jul 31 15:59:06 CST 2018
     */
    List<ErpVipInfo> selectByExample(ErpVipInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_info
     *
     * @mbg.generated Tue Jul 31 15:59:06 CST 2018
     */
    ErpVipInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_info
     *
     * @mbg.generated Tue Jul 31 15:59:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") ErpVipInfo record, @Param("example") ErpVipInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_info
     *
     * @mbg.generated Tue Jul 31 15:59:06 CST 2018
     */
    int updateByExample(@Param("record") ErpVipInfo record, @Param("example") ErpVipInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_info
     *
     * @mbg.generated Tue Jul 31 15:59:06 CST 2018
     */
    int updateByPrimaryKeySelective(ErpVipInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_vip_info
     *
     * @mbg.generated Tue Jul 31 15:59:06 CST 2018
     */
    int updateByPrimaryKey(ErpVipInfo record);
}