package com.solo.erp.dao.model;

import java.io.Serializable;
import java.util.Date;

public class ErpMenuInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_menu_info.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_menu_info.url
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_menu_info.path
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_menu_info.name
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_menu_info.component
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_menu_info.icon
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_menu_info.parent_id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_menu_info.is_enable
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Boolean isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_menu_info.require_auth
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String requireAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_menu_info.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_menu_info.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table erp_menu_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_menu_info.id
     *
     * @return the value of erp_menu_info.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_menu_info.id
     *
     * @param id the value for erp_menu_info.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_menu_info.url
     *
     * @return the value of erp_menu_info.url
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_menu_info.url
     *
     * @param url the value for erp_menu_info.url
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_menu_info.path
     *
     * @return the value of erp_menu_info.path
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_menu_info.path
     *
     * @param path the value for erp_menu_info.path
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_menu_info.name
     *
     * @return the value of erp_menu_info.name
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_menu_info.name
     *
     * @param name the value for erp_menu_info.name
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_menu_info.component
     *
     * @return the value of erp_menu_info.component
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_menu_info.component
     *
     * @param component the value for erp_menu_info.component
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_menu_info.icon
     *
     * @return the value of erp_menu_info.icon
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_menu_info.icon
     *
     * @param icon the value for erp_menu_info.icon
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_menu_info.parent_id
     *
     * @return the value of erp_menu_info.parent_id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_menu_info.parent_id
     *
     * @param parentId the value for erp_menu_info.parent_id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_menu_info.is_enable
     *
     * @return the value of erp_menu_info.is_enable
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_menu_info.is_enable
     *
     * @param isEnable the value for erp_menu_info.is_enable
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_menu_info.require_auth
     *
     * @return the value of erp_menu_info.require_auth
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getRequireAuth() {
        return requireAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_menu_info.require_auth
     *
     * @param requireAuth the value for erp_menu_info.require_auth
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setRequireAuth(String requireAuth) {
        this.requireAuth = requireAuth == null ? null : requireAuth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_menu_info.gmt_create
     *
     * @return the value of erp_menu_info.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_menu_info.gmt_create
     *
     * @param gmtCreate the value for erp_menu_info.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_menu_info.gmt_modified
     *
     * @return the value of erp_menu_info.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_menu_info.gmt_modified
     *
     * @param gmtModified the value for erp_menu_info.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}