package com.solo.erp.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ErpOrderDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_detail.id
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_detail.order_no
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_detail.product_name
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_detail.product_sn
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private String productSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_detail.product_no
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_detail.size
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_detail.color
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_detail.num
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_detail.real_price
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private BigDecimal realPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_detail.order_score
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private BigDecimal orderScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_detail.gmt_create
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_detail.gmt_modified
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_detail.order_date
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table erp_order_detail
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_detail.id
     *
     * @return the value of erp_order_detail.id
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_detail.id
     *
     * @param id the value for erp_order_detail.id
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_detail.order_no
     *
     * @return the value of erp_order_detail.order_no
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_detail.order_no
     *
     * @param orderNo the value for erp_order_detail.order_no
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_detail.product_name
     *
     * @return the value of erp_order_detail.product_name
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_detail.product_name
     *
     * @param productName the value for erp_order_detail.product_name
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_detail.product_sn
     *
     * @return the value of erp_order_detail.product_sn
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public String getProductSn() {
        return productSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_detail.product_sn
     *
     * @param productSn the value for erp_order_detail.product_sn
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setProductSn(String productSn) {
        this.productSn = productSn == null ? null : productSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_detail.product_no
     *
     * @return the value of erp_order_detail.product_no
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_detail.product_no
     *
     * @param productNo the value for erp_order_detail.product_no
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_detail.size
     *
     * @return the value of erp_order_detail.size
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_detail.size
     *
     * @param size the value for erp_order_detail.size
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_detail.color
     *
     * @return the value of erp_order_detail.color
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_detail.color
     *
     * @param color the value for erp_order_detail.color
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_detail.num
     *
     * @return the value of erp_order_detail.num
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_detail.num
     *
     * @param num the value for erp_order_detail.num
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_detail.real_price
     *
     * @return the value of erp_order_detail.real_price
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public BigDecimal getRealPrice() {
        return realPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_detail.real_price
     *
     * @param realPrice the value for erp_order_detail.real_price
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setRealPrice(BigDecimal realPrice) {
        this.realPrice = realPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_detail.order_score
     *
     * @return the value of erp_order_detail.order_score
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public BigDecimal getOrderScore() {
        return orderScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_detail.order_score
     *
     * @param orderScore the value for erp_order_detail.order_score
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setOrderScore(BigDecimal orderScore) {
        this.orderScore = orderScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_detail.gmt_create
     *
     * @return the value of erp_order_detail.gmt_create
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_detail.gmt_create
     *
     * @param gmtCreate the value for erp_order_detail.gmt_create
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_detail.gmt_modified
     *
     * @return the value of erp_order_detail.gmt_modified
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_detail.gmt_modified
     *
     * @param gmtModified the value for erp_order_detail.gmt_modified
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_detail.order_date
     *
     * @return the value of erp_order_detail.order_date
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_detail.order_date
     *
     * @param orderDate the value for erp_order_detail.order_date
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
}