package com.solo.erp.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ErpOrderInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.id
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.shop_id
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.staff_id
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private Integer staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.staff_name
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private String staffName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.order_no
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.order_status
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.pay_type
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.pay_amount
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private BigDecimal payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.pay_score
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private BigDecimal payScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.total_amount
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.order_score
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private BigDecimal orderScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.is_refund
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private Boolean isRefund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.remark
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.origin_order_no
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private String originOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.is_invoice
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private Boolean isInvoice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.invoice_remark
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private String invoiceRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.gmt_create
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.gmt_modified
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_order_info.order_date
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table erp_order_info
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.id
     *
     * @return the value of erp_order_info.id
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.id
     *
     * @param id the value for erp_order_info.id
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.shop_id
     *
     * @return the value of erp_order_info.shop_id
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.shop_id
     *
     * @param shopId the value for erp_order_info.shop_id
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.staff_id
     *
     * @return the value of erp_order_info.staff_id
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.staff_id
     *
     * @param staffId the value for erp_order_info.staff_id
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.staff_name
     *
     * @return the value of erp_order_info.staff_name
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.staff_name
     *
     * @param staffName the value for erp_order_info.staff_name
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.order_no
     *
     * @return the value of erp_order_info.order_no
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.order_no
     *
     * @param orderNo the value for erp_order_info.order_no
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.order_status
     *
     * @return the value of erp_order_info.order_status
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.order_status
     *
     * @param orderStatus the value for erp_order_info.order_status
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.pay_type
     *
     * @return the value of erp_order_info.pay_type
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.pay_type
     *
     * @param payType the value for erp_order_info.pay_type
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.pay_amount
     *
     * @return the value of erp_order_info.pay_amount
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.pay_amount
     *
     * @param payAmount the value for erp_order_info.pay_amount
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.pay_score
     *
     * @return the value of erp_order_info.pay_score
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public BigDecimal getPayScore() {
        return payScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.pay_score
     *
     * @param payScore the value for erp_order_info.pay_score
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setPayScore(BigDecimal payScore) {
        this.payScore = payScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.total_amount
     *
     * @return the value of erp_order_info.total_amount
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.total_amount
     *
     * @param totalAmount the value for erp_order_info.total_amount
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.order_score
     *
     * @return the value of erp_order_info.order_score
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public BigDecimal getOrderScore() {
        return orderScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.order_score
     *
     * @param orderScore the value for erp_order_info.order_score
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setOrderScore(BigDecimal orderScore) {
        this.orderScore = orderScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.is_refund
     *
     * @return the value of erp_order_info.is_refund
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public Boolean getIsRefund() {
        return isRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.is_refund
     *
     * @param isRefund the value for erp_order_info.is_refund
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setIsRefund(Boolean isRefund) {
        this.isRefund = isRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.remark
     *
     * @return the value of erp_order_info.remark
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.remark
     *
     * @param remark the value for erp_order_info.remark
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.origin_order_no
     *
     * @return the value of erp_order_info.origin_order_no
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public String getOriginOrderNo() {
        return originOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.origin_order_no
     *
     * @param originOrderNo the value for erp_order_info.origin_order_no
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setOriginOrderNo(String originOrderNo) {
        this.originOrderNo = originOrderNo == null ? null : originOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.is_invoice
     *
     * @return the value of erp_order_info.is_invoice
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public Boolean getIsInvoice() {
        return isInvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.is_invoice
     *
     * @param isInvoice the value for erp_order_info.is_invoice
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setIsInvoice(Boolean isInvoice) {
        this.isInvoice = isInvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.invoice_remark
     *
     * @return the value of erp_order_info.invoice_remark
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public String getInvoiceRemark() {
        return invoiceRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.invoice_remark
     *
     * @param invoiceRemark the value for erp_order_info.invoice_remark
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setInvoiceRemark(String invoiceRemark) {
        this.invoiceRemark = invoiceRemark == null ? null : invoiceRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.gmt_create
     *
     * @return the value of erp_order_info.gmt_create
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.gmt_create
     *
     * @param gmtCreate the value for erp_order_info.gmt_create
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.gmt_modified
     *
     * @return the value of erp_order_info.gmt_modified
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.gmt_modified
     *
     * @param gmtModified the value for erp_order_info.gmt_modified
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_order_info.order_date
     *
     * @return the value of erp_order_info.order_date
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_order_info.order_date
     *
     * @param orderDate the value for erp_order_info.order_date
     *
     * @mbg.generated Tue Jul 31 14:52:19 CST 2018
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
}