package com.solo.erp.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ErpProductInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_product_info.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_product_info.product_sn
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String productSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_product_info.product_name
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_product_info.product_img
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String productImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_product_info.product_thums
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String productThums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_product_info.brand_name
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_product_info.tag_price
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private BigDecimal tagPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_product_info.real_price
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private BigDecimal realPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_product_info.size
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_product_info.color
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_product_info.discount
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Integer discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_product_info.remark
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_product_info.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_product_info.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table erp_product_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_product_info.id
     *
     * @return the value of erp_product_info.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_product_info.id
     *
     * @param id the value for erp_product_info.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_product_info.product_sn
     *
     * @return the value of erp_product_info.product_sn
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getProductSn() {
        return productSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_product_info.product_sn
     *
     * @param productSn the value for erp_product_info.product_sn
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setProductSn(String productSn) {
        this.productSn = productSn == null ? null : productSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_product_info.product_name
     *
     * @return the value of erp_product_info.product_name
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_product_info.product_name
     *
     * @param productName the value for erp_product_info.product_name
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_product_info.product_img
     *
     * @return the value of erp_product_info.product_img
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getProductImg() {
        return productImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_product_info.product_img
     *
     * @param productImg the value for erp_product_info.product_img
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setProductImg(String productImg) {
        this.productImg = productImg == null ? null : productImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_product_info.product_thums
     *
     * @return the value of erp_product_info.product_thums
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getProductThums() {
        return productThums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_product_info.product_thums
     *
     * @param productThums the value for erp_product_info.product_thums
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setProductThums(String productThums) {
        this.productThums = productThums == null ? null : productThums.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_product_info.brand_name
     *
     * @return the value of erp_product_info.brand_name
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_product_info.brand_name
     *
     * @param brandName the value for erp_product_info.brand_name
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_product_info.tag_price
     *
     * @return the value of erp_product_info.tag_price
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public BigDecimal getTagPrice() {
        return tagPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_product_info.tag_price
     *
     * @param tagPrice the value for erp_product_info.tag_price
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setTagPrice(BigDecimal tagPrice) {
        this.tagPrice = tagPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_product_info.real_price
     *
     * @return the value of erp_product_info.real_price
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public BigDecimal getRealPrice() {
        return realPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_product_info.real_price
     *
     * @param realPrice the value for erp_product_info.real_price
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setRealPrice(BigDecimal realPrice) {
        this.realPrice = realPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_product_info.size
     *
     * @return the value of erp_product_info.size
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_product_info.size
     *
     * @param size the value for erp_product_info.size
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_product_info.color
     *
     * @return the value of erp_product_info.color
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_product_info.color
     *
     * @param color the value for erp_product_info.color
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_product_info.discount
     *
     * @return the value of erp_product_info.discount
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_product_info.discount
     *
     * @param discount the value for erp_product_info.discount
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_product_info.remark
     *
     * @return the value of erp_product_info.remark
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_product_info.remark
     *
     * @param remark the value for erp_product_info.remark
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_product_info.gmt_create
     *
     * @return the value of erp_product_info.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_product_info.gmt_create
     *
     * @param gmtCreate the value for erp_product_info.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_product_info.gmt_modified
     *
     * @return the value of erp_product_info.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_product_info.gmt_modified
     *
     * @param gmtModified the value for erp_product_info.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}