package com.solo.erp.dao.model;

import java.io.Serializable;
import java.util.Date;

public class ErpRoleInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_role_info.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_role_info.name
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_role_info.name_zn
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String nameZn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_role_info.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_role_info.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_role_info.is_enable
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Boolean isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table erp_role_info
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_role_info.id
     *
     * @return the value of erp_role_info.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_role_info.id
     *
     * @param id the value for erp_role_info.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_role_info.name
     *
     * @return the value of erp_role_info.name
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_role_info.name
     *
     * @param name the value for erp_role_info.name
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_role_info.name_zn
     *
     * @return the value of erp_role_info.name_zn
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getNameZn() {
        return nameZn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_role_info.name_zn
     *
     * @param nameZn the value for erp_role_info.name_zn
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setNameZn(String nameZn) {
        this.nameZn = nameZn == null ? null : nameZn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_role_info.gmt_create
     *
     * @return the value of erp_role_info.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_role_info.gmt_create
     *
     * @param gmtCreate the value for erp_role_info.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_role_info.gmt_modified
     *
     * @return the value of erp_role_info.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_role_info.gmt_modified
     *
     * @param gmtModified the value for erp_role_info.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_role_info.is_enable
     *
     * @return the value of erp_role_info.is_enable
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_role_info.is_enable
     *
     * @param isEnable the value for erp_role_info.is_enable
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }
}