package com.solo.erp.dao.model;

import java.io.Serializable;
import java.util.Date;

public class ErpRoleMenuRel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_role_menu_rel.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_role_menu_rel.role_id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_role_menu_rel.menu_id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_role_menu_rel.is_enable
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Boolean isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_role_menu_rel.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_role_menu_rel.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table erp_role_menu_rel
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_role_menu_rel.id
     *
     * @return the value of erp_role_menu_rel.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_role_menu_rel.id
     *
     * @param id the value for erp_role_menu_rel.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_role_menu_rel.role_id
     *
     * @return the value of erp_role_menu_rel.role_id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_role_menu_rel.role_id
     *
     * @param roleId the value for erp_role_menu_rel.role_id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_role_menu_rel.menu_id
     *
     * @return the value of erp_role_menu_rel.menu_id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_role_menu_rel.menu_id
     *
     * @param menuId the value for erp_role_menu_rel.menu_id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_role_menu_rel.is_enable
     *
     * @return the value of erp_role_menu_rel.is_enable
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_role_menu_rel.is_enable
     *
     * @param isEnable the value for erp_role_menu_rel.is_enable
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_role_menu_rel.gmt_create
     *
     * @return the value of erp_role_menu_rel.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_role_menu_rel.gmt_create
     *
     * @param gmtCreate the value for erp_role_menu_rel.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_role_menu_rel.gmt_modified
     *
     * @return the value of erp_role_menu_rel.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_role_menu_rel.gmt_modified
     *
     * @param gmtModified the value for erp_role_menu_rel.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}