package com.solo.erp.dao.model;

import java.io.Serializable;
import java.util.Date;

public class ErpShopInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_shop_info.id
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_shop_info.shop_name
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_shop_info.shop_address
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    private String shopAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_shop_info.gmt_create
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_shop_info.gmt_modified
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_shop_info.is_enable
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    private Boolean isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_shop_info.parent_id
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table erp_shop_info
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_shop_info.id
     *
     * @return the value of erp_shop_info.id
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_shop_info.id
     *
     * @param id the value for erp_shop_info.id
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_shop_info.shop_name
     *
     * @return the value of erp_shop_info.shop_name
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_shop_info.shop_name
     *
     * @param shopName the value for erp_shop_info.shop_name
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_shop_info.shop_address
     *
     * @return the value of erp_shop_info.shop_address
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    public String getShopAddress() {
        return shopAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_shop_info.shop_address
     *
     * @param shopAddress the value for erp_shop_info.shop_address
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    public void setShopAddress(String shopAddress) {
        this.shopAddress = shopAddress == null ? null : shopAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_shop_info.gmt_create
     *
     * @return the value of erp_shop_info.gmt_create
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_shop_info.gmt_create
     *
     * @param gmtCreate the value for erp_shop_info.gmt_create
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_shop_info.gmt_modified
     *
     * @return the value of erp_shop_info.gmt_modified
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_shop_info.gmt_modified
     *
     * @param gmtModified the value for erp_shop_info.gmt_modified
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_shop_info.is_enable
     *
     * @return the value of erp_shop_info.is_enable
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_shop_info.is_enable
     *
     * @param isEnable the value for erp_shop_info.is_enable
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_shop_info.parent_id
     *
     * @return the value of erp_shop_info.parent_id
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_shop_info.parent_id
     *
     * @param parentId the value for erp_shop_info.parent_id
     *
     * @mbg.generated Fri Aug 03 15:33:38 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}