package com.solo.erp.dao.model;

import java.io.Serializable;
import java.util.Date;

public class ErpStaffInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_staff_info.id
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_staff_info.login_name
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_staff_info.login_pwd
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private String loginPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_staff_info.staff_name
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private String staffName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_staff_info.staff_no
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private String staffNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_staff_info.staff_photo
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private String staffPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_staff_info.mobile
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_staff_info.address
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_staff_info.shop_id
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_staff_info.is_enable
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private Boolean isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_staff_info.gmt_create
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_staff_info.gmt_modified
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_staff_info.sex
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_staff_info.brithday
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private Date brithday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_staff_info.shop_name
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_staff_info.last_time
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private Date lastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_staff_info.last_ip
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private String lastIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table erp_staff_info
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff_info.id
     *
     * @return the value of erp_staff_info.id
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff_info.id
     *
     * @param id the value for erp_staff_info.id
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff_info.login_name
     *
     * @return the value of erp_staff_info.login_name
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff_info.login_name
     *
     * @param loginName the value for erp_staff_info.login_name
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff_info.login_pwd
     *
     * @return the value of erp_staff_info.login_pwd
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff_info.login_pwd
     *
     * @param loginPwd the value for erp_staff_info.login_pwd
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff_info.staff_name
     *
     * @return the value of erp_staff_info.staff_name
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff_info.staff_name
     *
     * @param staffName the value for erp_staff_info.staff_name
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff_info.staff_no
     *
     * @return the value of erp_staff_info.staff_no
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public String getStaffNo() {
        return staffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff_info.staff_no
     *
     * @param staffNo the value for erp_staff_info.staff_no
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public void setStaffNo(String staffNo) {
        this.staffNo = staffNo == null ? null : staffNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff_info.staff_photo
     *
     * @return the value of erp_staff_info.staff_photo
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public String getStaffPhoto() {
        return staffPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff_info.staff_photo
     *
     * @param staffPhoto the value for erp_staff_info.staff_photo
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public void setStaffPhoto(String staffPhoto) {
        this.staffPhoto = staffPhoto == null ? null : staffPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff_info.mobile
     *
     * @return the value of erp_staff_info.mobile
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff_info.mobile
     *
     * @param mobile the value for erp_staff_info.mobile
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff_info.address
     *
     * @return the value of erp_staff_info.address
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff_info.address
     *
     * @param address the value for erp_staff_info.address
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff_info.shop_id
     *
     * @return the value of erp_staff_info.shop_id
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff_info.shop_id
     *
     * @param shopId the value for erp_staff_info.shop_id
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff_info.is_enable
     *
     * @return the value of erp_staff_info.is_enable
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff_info.is_enable
     *
     * @param isEnable the value for erp_staff_info.is_enable
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff_info.gmt_create
     *
     * @return the value of erp_staff_info.gmt_create
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff_info.gmt_create
     *
     * @param gmtCreate the value for erp_staff_info.gmt_create
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff_info.gmt_modified
     *
     * @return the value of erp_staff_info.gmt_modified
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff_info.gmt_modified
     *
     * @param gmtModified the value for erp_staff_info.gmt_modified
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff_info.sex
     *
     * @return the value of erp_staff_info.sex
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff_info.sex
     *
     * @param sex the value for erp_staff_info.sex
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff_info.brithday
     *
     * @return the value of erp_staff_info.brithday
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public Date getBrithday() {
        return brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff_info.brithday
     *
     * @param brithday the value for erp_staff_info.brithday
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public void setBrithday(Date brithday) {
        this.brithday = brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff_info.shop_name
     *
     * @return the value of erp_staff_info.shop_name
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff_info.shop_name
     *
     * @param shopName the value for erp_staff_info.shop_name
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff_info.last_time
     *
     * @return the value of erp_staff_info.last_time
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff_info.last_time
     *
     * @param lastTime the value for erp_staff_info.last_time
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff_info.last_ip
     *
     * @return the value of erp_staff_info.last_ip
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff_info.last_ip
     *
     * @param lastIp the value for erp_staff_info.last_ip
     *
     * @mbg.generated Fri Aug 03 09:29:39 CST 2018
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }
}