package com.solo.erp.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ErpVipRanks implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_vip_ranks.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_vip_ranks.rank_name
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String rankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_vip_ranks.start_score
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private BigDecimal startScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_vip_ranks.end_score
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private BigDecimal endScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_vip_ranks.rebate
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Integer rebate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_vip_ranks.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_vip_ranks.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_vip_ranks.is_enable
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Boolean isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table erp_vip_ranks
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_vip_ranks.id
     *
     * @return the value of erp_vip_ranks.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_vip_ranks.id
     *
     * @param id the value for erp_vip_ranks.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_vip_ranks.rank_name
     *
     * @return the value of erp_vip_ranks.rank_name
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getRankName() {
        return rankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_vip_ranks.rank_name
     *
     * @param rankName the value for erp_vip_ranks.rank_name
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setRankName(String rankName) {
        this.rankName = rankName == null ? null : rankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_vip_ranks.start_score
     *
     * @return the value of erp_vip_ranks.start_score
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public BigDecimal getStartScore() {
        return startScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_vip_ranks.start_score
     *
     * @param startScore the value for erp_vip_ranks.start_score
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setStartScore(BigDecimal startScore) {
        this.startScore = startScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_vip_ranks.end_score
     *
     * @return the value of erp_vip_ranks.end_score
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public BigDecimal getEndScore() {
        return endScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_vip_ranks.end_score
     *
     * @param endScore the value for erp_vip_ranks.end_score
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setEndScore(BigDecimal endScore) {
        this.endScore = endScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_vip_ranks.rebate
     *
     * @return the value of erp_vip_ranks.rebate
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Integer getRebate() {
        return rebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_vip_ranks.rebate
     *
     * @param rebate the value for erp_vip_ranks.rebate
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setRebate(Integer rebate) {
        this.rebate = rebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_vip_ranks.gmt_create
     *
     * @return the value of erp_vip_ranks.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_vip_ranks.gmt_create
     *
     * @param gmtCreate the value for erp_vip_ranks.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_vip_ranks.gmt_modified
     *
     * @return the value of erp_vip_ranks.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_vip_ranks.gmt_modified
     *
     * @param gmtModified the value for erp_vip_ranks.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_vip_ranks.is_enable
     *
     * @return the value of erp_vip_ranks.is_enable
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_vip_ranks.is_enable
     *
     * @param isEnable the value for erp_vip_ranks.is_enable
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }
}