package com.solo.erp.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ErpVipScore implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_vip_score.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_vip_score.vip_id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Integer vipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_vip_score.score
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private BigDecimal score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_vip_score.data_src
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String dataSrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_vip_score.data_id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String dataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_vip_score.remark
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_vip_score.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_vip_score.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table erp_vip_score
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_vip_score.id
     *
     * @return the value of erp_vip_score.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_vip_score.id
     *
     * @param id the value for erp_vip_score.id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_vip_score.vip_id
     *
     * @return the value of erp_vip_score.vip_id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Integer getVipId() {
        return vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_vip_score.vip_id
     *
     * @param vipId the value for erp_vip_score.vip_id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setVipId(Integer vipId) {
        this.vipId = vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_vip_score.score
     *
     * @return the value of erp_vip_score.score
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_vip_score.score
     *
     * @param score the value for erp_vip_score.score
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_vip_score.data_src
     *
     * @return the value of erp_vip_score.data_src
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getDataSrc() {
        return dataSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_vip_score.data_src
     *
     * @param dataSrc the value for erp_vip_score.data_src
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setDataSrc(String dataSrc) {
        this.dataSrc = dataSrc == null ? null : dataSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_vip_score.data_id
     *
     * @return the value of erp_vip_score.data_id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_vip_score.data_id
     *
     * @param dataId the value for erp_vip_score.data_id
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setDataId(String dataId) {
        this.dataId = dataId == null ? null : dataId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_vip_score.remark
     *
     * @return the value of erp_vip_score.remark
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_vip_score.remark
     *
     * @param remark the value for erp_vip_score.remark
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_vip_score.gmt_create
     *
     * @return the value of erp_vip_score.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_vip_score.gmt_create
     *
     * @param gmtCreate the value for erp_vip_score.gmt_create
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_vip_score.gmt_modified
     *
     * @return the value of erp_vip_score.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_vip_score.gmt_modified
     *
     * @param gmtModified the value for erp_vip_score.gmt_modified
     *
     * @mbg.generated Wed Jul 11 11:10:21 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}